mailmanPackages.python.pkgs.hiredis: fix override
	error: fetchFromGitHub requires one of either `rev` or `tag` to be provided (not both).

Fixes: 0cd04d30366f ("treewide: migrate fetchgit `rev = "refs/tags/..."` to `tag`")